### ISSUE TITLE
Pattern Matching Couchbase Lite

### ISSUE THREAD

**Issue by kundan7560** [couchbase/couchbase-lite-android#1198]
Hi,
I am new in Couchbase lite. i am wondering how to write pattern matching query in Couchbase . similar to 'LIKE' pattern in SQL.

Suppose I have a document with id, name, and email. i want to filter the documents that having the name starts with letter 'A'

Thanks in advance

**Comment by jamiltz** [comment]
You can refer to this example to setup the query https://developer.couchbase.com/documentation/mobile/2.0/guides/couchbase-lite/native-api/query/index.html?language=java

But instead of using the `equalTo` operator you can use the `like` operator http://docs.couchbase.com/mobile/2.0/couchbase-lite-java/db008/com/couchbase/lite/Expression.html#like-java.lang.Object-. Like in SQL, the `%` character can be used as a wildcard.

Thanks for the feedback, we will include an example of it in the docs.

**Comment by kundan7560** [comment]
Hi Jamiltz,
Thanks for your comments. could you please like to provide sample code for using like operator in Couchbase Database Lite in android.

**Comment by jamiltz** [comment]
@kundan7560 I forgot to ask, did you ask that question for the 2.0 or 1.x API?

**Comment by kundan7560** [comment]
@jamiltz I have added the below dependency
 compile 'com.couchbase.lite:couchbase-lite-android:1.4.0' and I need to setup the code for this. if you find any solution always welcome.
Thank You

**Comment by jamiltz** [comment]
You can use the `prefixMatchLevel` operator in this case https://developer.couchbase.com/documentation/mobile/1.4/guides/couchbase-lite/native-api/query/index.html#creating-and-configuring-queries
