### ISSUE TITLE
database.exists enforces the directory parameter as mandatory

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-android#1497]
CBL2.0

The directory parameter is optional in iOS and mandatory in Android. The behavior is not consistent.
Android version of exists:
```
public static boolean exists(String name, File directory) {
        if (name == null || directory == null)
            throw new IllegalArgumentException("a name parameter and/or a dir parameter are null.");
        return getDatabasePath(directory, name).exists();
    }
```
ios version of exists:
```
public class func exists(withName name: String, inDirectory directory: String? = nil) -> Bool {
        return CBLDatabase.databaseExists(name, inDirectory: directory)
    }
```

According to @pasin iOS is correct. When the directly is null, the API will try to check at the database at the default location. Refer https://github.com/couchbase/couchbase-lite-ios/issues/2002

**Comment by hideki** [comment]
@raghusarangapani 

CBL Android 2.0 does not support `null` as `directory` parameter because CBL cannot obtain default directly without [Context](https://developer.android.com/reference/android/content/Context.html). However other platforms might be able to.

We need to explain this difference in the documentation.
