### ISSUE TITLE
Replication doesn't sync docs for update docs

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-android#1551]
This issue is in reference with - https://github.com/couchbase/sync_gateway/issues/3239

Here are the steps to reproduce - 

1. Setup cluster environment with an app, a SG and a CBS connected to each other.
2. The app should run a replication with below configuration -
 a. setContinous - true
 b. setAuthenticator - username, password (basic authenticator)
 c. setReplicatorType - PUSH_AND_PULL

3. Create 1000 docs in CBL app. Check if docs are getting synced to SG/CBS
4. Start updating random docs for a certain period of time. Check if the updates are getting reflected in SG/CBS. This is the situation where we are facing the issue. I can validate that the doc content in CBL app changes, but, same update doesn't get sync to SG/CBS.

This is the reference app I using for this testing (branch cbl2.0_android)- https://github.com/couchbaselabs/mobile-testkit/blob/cbl2.0_android/apps/testkit.java/testkit.java.android/Tests/AndroidClient/app/src/main/java/com/couchbase/androidclient/MainActivity.java

**Comment by hideki** [comment]
Original test code set continuous true after  `ReplicatorConfig.Builder` built the replicator configuration.

**Comment by stecapra** [comment]
This issue is in reference to this topic [sync-gateway-not-push-latest-document-if-device-is-not-connected](https://forums.couchbase.com/t/sync-gateway-not-push-latest-document-if-device-is-not-connected/15710/10).

Steps to reproduce:

1. Open the app
2. The app should run a replication with below configuration -
a. setContinous - true
b. setAuthenticator - username, password (basic authenticator)
3. Turn off the wifi and kill the app
4. Add two documents from sync gateway console
5. Turn on the wifi and reopen the app

Only the first document is pulled from sync gateway server to the device.

Database changeListener `change.getDocumentIDs` shows only the first id.

The logs and the class of database instance can be found [here](https://gist.github.com/stecapra/7f6b9f5818c882f3975a9b0a65be2b60)

**Comment by hideki** [comment]
It seems reopened the wrong ticket.

**Comment by hideki** [comment]
REF: https://github.com/couchbase/couchbase-lite-android/issues/1586
