### ISSUE TITLE
2.0: documents created when Android app is offline  not pulled down properly from SGW 

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-android#1586]
Originally reported on forums :https://forums.couchbase.com/t/sync-gateway-not-push-latest-document-if-device-is-not-connected/15710/9

version  : DB021, Android
sync gateway : v 1.5

Steps 

- kill the app
- create two docs with sync gateway
- re-open the app
- query all the documents in the db, and only the first one has been returned
- Update the second doc on sync gateway
- the second doc now gets synced up

(Another observation :"Another thing i notice is that if i add for example 5 documents when the device is offline, and then came back online, sync gateway push only the first four docs. ")

**Comment by hideki** [comment]
Original comment by @stecapra

https://github.com/couchbase/couchbase-lite-android/issues/1551#issuecomment-363807714

--------------------------------

This issue is in reference to this topic [sync-gateway-not-push-latest-document-if-device-is-not-connected](https://forums.couchbase.com/t/sync-gateway-not-push-latest-document-if-device-is-not-connected/15710/10).

Steps to reproduce:

1. Open the app
2. The app should run a replication with below configuration -
a. setContinous - true
b. setAuthenticator - username, password (basic authenticator)
3. Turn off the wifi and kill the app
4. Add two documents from sync gateway console
5. Turn on the wifi and reopen the app

Only the first document is pulled from sync gateway server to the device.

Database changeListener `change.getDocumentIDs` shows only the first id.

The logs and the class of database instance can be found [here](https://gist.github.com/stecapra/7f6b9f5818c882f3975a9b0a65be2b60)

**Comment by hideki** [comment]
I added the unit test that pulls replicate data from Sync Gateway and runs the query in DatabaseChangeLisstener. I could not reproduce the issue that was described in this ticket.
https://github.com/couchbase/couchbase-lite-android/blob/47b92f20ad7170a57c9f45b094f6cd76485033dc/android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/ReplicatorWithSyncGatewayDBTest.java#L408-L459

**Comment by rajagp** [comment]
How are you testing the wifi offline case with the test?

**Comment by hideki** [comment]
@rajagp 
In the reproduction steps, wifi offline/online is not mentioned. So test does not cover wifi online/offline.

To reproduce the problem, wifi online/offline is required?

**Comment by stecapra** [comment]
I'm guessing that `remote_PUT_db` is an HTTP request, and you are making this request when the app is open. 
The problem arises when i use directly the sync gateway interface and the app is killed(and the wifi is turn off). 

I'm just guessing, though

**Comment by hideki** [comment]
Hi @stecapra  and @rajagp,

I tested this scenario with using [Todo sample application](https://github.com/couchbaselabs/mobile-training-todo/tree/master/android) with CBL 2.0 DB022 and Sync Gateway Beta build.

Following is my test steps.
1. Connect two real devices to Sync Gateway.
2. Make one device (Nexus 6) offline (Disabled Wifi).
3. From Another Device (Nexus 6P), create **multiple** documents
4. Make Nexus 6 online, enabled wifi.
5. Confirm Nexus 6 has all updates.

![1586](https://user-images.githubusercontent.com/15889/36395403-daa2df7c-156d-11e8-8758-83a7aa7c8df1.gif)

Do I miss something?

**Comment by hideki** [comment]
I also tested the scenario that creating multiple documents from OFFLINE devices. I can not observe the replication issue either.

**Comment by stecapra** [comment]
Hi, 
The steps are right, so in that case the problem could be in my configuration. 
Just to know, did you test everything under walrus server? Or did you use a CB server with a specific bucket? 
Is there any param in the server configuration that could raise this problem?

**Comment by hideki** [comment]
> Just to know, did you test everything under walrus server? Or did you use a CB server with a specific bucket?

Sync Gateway -> Walrus
sync gateway config for todo -> https://gist.github.com/hideki/a5dc40be716be455616e7b6601db5e3f

**Comment by stecapra** [comment]
HI, i've tested the application using walrus server and the problem is still there.
I tried to use [todo app](https://github.com/couchbaselabs/mobile-training-todo/tree/master/android), changing the CBL version to 

CBL 2.0.0-DB021

I've user the most basic sync_gateway configuration, and the class that handle the database as simple as possible.
I didn't use DB022 because, if i used
```
"unsupported": {
        "replicator_2":true
      },
``` 
in sync config, it triggered me this exception:
```
02-21 13:26:11.509 27646-27668/com.couchbase.todo E/AndroidRuntime: FATAL EXCEPTION: Thread-3284
                                                                    Process: com.couchbase.todo, PID: 27646
                                                                    java.lang.IllegalArgumentException: Code 1006 is reserved and may not be used.
                                                                        at okhttp3.internal.ws.WebSocketProtocol.validateCloseCode(WebSocketProtocol.java:120)
                                                                        at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:401)
                                                                        at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:397)
                                                                        at com.couchbase.lite.internal.replicator.CBLWebSocket.requestClose(CBLWebSocket.java:226)
                                                                        at com.couchbase.litecore.C4Socket.requestClose(C4Socket.java:155)
```
Instead, if i didn't used unsupported config, it triggered me:
```
02-21 13:28:05.706 27877-27904/com.couchbase.todo E/WebSocket: WebSocketListener.onFailure() response -> Response{protocol=http/1.1, code=404, message=Not Found, url=http://192.168.1.16:4984/todo/_blipsync}
                                                               java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
                                                                   at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:219)
                                                                   at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:186)
                                                                   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
                                                                   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                   at java.lang.Thread.run(Thread.java:818)

```
So i decide to tested it out with DB021 and blip connection.
Here you find the class and the sync config [here](https://gist.github.com/stecapra/83811f4f446fa6b5ef48e02fef0cfed1)

What do you think? I'm missing something?

**Comment by hideki** [comment]
@stecapra 
DB022 requires Sync Gateway Beta build from Couchbase download site.
https://www.couchbase.com/downloads

**Comment by stecapra** [comment]
Ok, everything works fine now. It's seems that it was something about DB021. 
Thank you very much

**Comment by hideki** [comment]
@stecapra It is great to hear! thanks!
