### ISSUE TITLE
Attachment images added in ios do not show up in android

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-android#1611]
Originally https://github.com/couchbaselabs/mobile-training-todo/issues/173 filing in Android because that's how the issue was tagged.

Steps

Compiled ToDo app.
Installed on a Nexus 6p device.
Create a list and a task.
Add attachment image for the list on ios
Check the same task on android
Actual

Images attached in ios do not show up in android

**Comment by hideki** [comment]
@djpongh I believe this is App issue. But I will look into it.

**Comment by tleyden** [comment]
@djpongh I reproduced the issue and looked at it in the debugger, and can see that the issue is that it's calling Blob.getContent() on a blob that's bigger than the limit of 8k, and so it's a bug in mobile-training-todo rather than couchbase-lite-android.  The fix is that mobile-training-todo just needs to call the `getContentStream()` API instead.  

Moving back to https://github.com/couchbaselabs/mobile-training-todo/issues/173

**Comment by djpongh** [comment]
Thanks @tleyden !

**Comment by hideki** [comment]
https://github.com/couchbaselabs/couchbase-lite-apiv2/issues/204#issuecomment-368159473

iOS does size check to determine if it can be cached or not.

Java should have the same logic.
