### ISSUE TITLE
CBL android does not work with self signed certs (Empty Common Name (CN) is not supported)

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-android#1639]
### Builds 
CBL Android 2.0.0-365, SG 2.0.0-814, CBS 5.5.0-1992

### Issue
1. CBL 2.0 Android used to work with self signed certs at some point with certificate pinning. Here is a blog @rajagp wrote - https://blog.couchbase.com/certificate-pinning-android-with-couchbase-mobile/ back in Dec 2017.
2. The same steps now throws an error
```
03-06 15:06:06.121 2799-2830/com.couchbase.TestServerApp E/LiteCore [Sync]: {Repl#1} Got LiteCore error: server TLS certificate untrusted (6/8)
```
3. The solution seems to be to write a custom TrustManager that does not verify the certs and register it with C4Socket library that CBL android is using to talk to SG.
4. Currently there is no API exposed to register a TrustManager and hence self signed certs cannot be used.
5. App developers will develop apps in house with self signed certs before deploying it to production with trusted CA certs.

**Comment by hideki** [comment]
@raghusarangapani ,

SSL/HTTPS with a self-signed certificate failed because Common Name (CN) in the certificate and hostname (IP address) don't match. The CN value in the certificate file we use is 'localhost'. However, to access Sync Gateway on localhost from Android emulator, the test uses `10.0.2.2` instead of `localhost` as `localhost` in Android emulator is indicating Android device itself. 

https://www.ssl.com/faqs/common-name/

> The Common Name must be the same as the Web address you will be accessing when connecting to a secure site. 

Please retest SSL/HTTPS with self-signed with proper CN value for a test environment. With Android stack emulator, it is`10.0.2.2`. With Genymotion, `10.0.3.2`. With a real device, it will be the IP address of hostname that SG is running.

Please use 2.0.0-397 for testing. 2.0.0-397 has customized hostname verifier which allows IP address as default Hostname verifier provided by OkHttp does not allow IP address as a hostname
http://mobile.maven.couchbase.com/feeds/dev//com/couchbase/lite/couchbase-lite-android-ee/2.0.0-397

Blog Priya wrote is helpful. 
https://blog.couchbase.com/certificate-pinning-android-with-couchbase-mobile/

**Comment by raghusarangapani** [comment]
There is no CommonName in the certificate, I did not provide one. The same certificate works with ios and .net.

**Comment by raghusarangapani** [comment]
@pasin and @snej confirmed that as long as the certificate on SG and on the CBL ios are identical, replication over SSL will work. There is no separate CN validation. This is not the case with CBL Android.

**Comment by hideki** [comment]
Please verify the fix with 2.0.0-400 http://mobile.maven.couchbase.com/feeds/dev//com/couchbase/lite/couchbase-lite-android-ee/2.0.0-400

**Comment by pasin** [comment]
@hideki I'm wondering if it's possible that we wrap the default HostNameVerifier from okhttp and override only some parts for self-sign certificate verification so we don't need to copy code from okhttp.

**Comment by hideki** [comment]
@pasin It is not possible because a constructor is private.
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/tls/OkHostnameVerifier.java#L42

**Comment by raghusarangapani** [comment]
Verified with 2.0.0-401 :
Issue is fixed.
