### ISSUE TITLE
Heap corruption after several start/stops of the replicator

### ISSUE THREAD

**Issue by bailsp** [couchbase/couchbase-lite-android#1751]
I have been experiencing this problem on both non-continuous and continuous replicators. I have an application that requires users to sign in, authenticates using session id, starts a continuous replicator. When the user signs out, the replicator is stopped. The problem arises when a user has logged in (starting a replicator), logged out (stopped a replicator), then logs back in (starts a new replicator) etc... This crash seems to happen randomly in random intervals of logging in/out

`08-17 13:58:50.201 23704-23732/net.ordercheck_in A/libc: /Users/bailey/wkspaces/Android/project/libs/couchbase-lite-android/libs/couchbase-lite-core/vendor/fleece/Fleece/slice.cc:300: void fleece::alloc_slice::sharedBuffer::release(): assertion “((size_t)(this) & 0x07) == 0” failed
Fatal signal 6 (SIGABRT) at 0x00005c98 (code=-6), thread 23732 (t.ordercheck_in)`

More logs:
https://pastebin.com/t1fE3v71

Any more information that is needed can be provided. I can replicate this issue every time.

**Comment by bailsp** [comment]
@pasin @borrrden 

Any update on this?

**Comment by bailsp** [comment]
@borrrden it’s roughly 27 mb, I think the limit is 10mb. When I get to the office tomorrow morning I’ll upload it to another file sharing site

**Comment by bailsp** [comment]
@borrrden 

I've uploaded it to my Dropbox

https://www.dropbox.com/s/g6v1pg6yhvumdtw/couchbasecrash.zip?dl=0

**Comment by borrrden** [comment]
You could have easily trimmed the size way down by deleting the "build" folder before zipping it (just something to keep in mind).

How many times do I have to repeat the start and stop?  I deployed it to my ARM device (API 23) and was able to hit start and stop around 15 times with no incident.  I changed the version to 2.0.2 and the compile SDK to 27 but other than that it is the same.

**Comment by bailsp** [comment]
@borrrden 

Deploy it to a device that is running API 19 and a armeabi-v7a arch. 

Galaxy Nexus API 19 (Android 4.4.2, API 19) Emulator is a confirmed device that has been crashing

**Comment by borrrden** [comment]
I am able to reproduce on both arm and x86 emulators for API19 with the 2.1.0 RC, but not on API21.  This issue is too late to make it into 2.1, but we should be able to figure something out by building with the address sanitizer.  It somewhat makes sense to me about API19 only as opposed to 19 - 22 since there was a JVM switch that happened in API21.  

As far as "SNAPSHOT" goes I'm not convinced that it is going to be accurate.  Our maven feed is a bit messed up since it was used in a way that I didn't intend for it to be, so you might be pulling the higher sorted 2.1.0-DB001 (which is months old at this point) instead of a newer build (which actually shouldn't even be there but for now it is).

**Comment by bailsp** [comment]
So will The wait time for a release with the fix be months down the road?

**Comment by borrrden** [comment]
For a GA release, that is likely to be the case.  I imagine there will be a few preview releases before the GA release though, and as always this code is open source so you are welcome to build it yourself as well (maybe patch just the fix onto the 2.1 release commit).

**Comment by pasin** [comment]
ffc = fix-for-customer. It's an internal flag to indicate that the issue is reported by a customer.
