### ISSUE TITLE
Client Proxy Support

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-android#1773]
Test replication which client proxies, both WS and WSS.

**Comment by pasin** [comment]
Sending WebSocket requests with OKHTTP seems to work with proxy without any problems when using WSS (SSL) but not WS. When testing with Squid, Squid expects a tunnel (requested by sending CONNECT request) to be created when upgrading to WebSocket protocol, otherwise Upgrade headers will be not forwarded correctly. OKHTTP doesn't send CONNECT request if non SSL requests are used based on [this](https://github.com/square/okhttp/blob/8a01554770d10062bb9d24176a8166e88412fbe2/okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java#L159) and [this](https://github.com/square/okhttp/blob/5b37cda9e00626f43acf354df145fd452c3031f1/okhttp/src/main/java/okhttp3/Route.java#L80). I have created an issue at OKHTTP repository (https://github.com/square/okhttp/issues/4390).

I have discussed the issue with @adamcfraser, and we could put a workaround on the SG to automatically upgrade to use WebSocket without checking Upgrade header when _blicsync requests are received. However, we expect that most of the customers are using SSL in their production so we think we could defer to put the workaround and wait to see how OKHTTP responds to the ticket. Not to mention that we haven't received any complains about the issue from customers yet.

**Comment by pasin** [comment]
Note, some code change to setup proxy info is still required. I will commit the code change for that.

**Comment by pasin** [comment]
We could also send the CONNECT request when HTTP request and client Proxy are used. I think we should try that.

**Comment by pasin** [comment]
I have discussed this with @djpongh and we will put this as a known issue for iridium.
