### ISSUE TITLE
Get error status: 403 only when trying to update a document and calling setAttachment on the new revision

### ISSUE THREAD

**Issue by SaifJamilKhan** [couchbase/couchbase-lite-android#470]
Im trying to upload an image to a document, here is my code to upload the bitmap

                       
 ```java
if (bmp == null) {
    Timber.e("Bitmap loading failed");
    return;
  }
  ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
  bmp.compress(Bitmap.CompressFormat.JPEG, 75, outputStream);
  InputStream inputStream = new ByteArrayInputStream(outputStream.toByteArray());




  Document doc = database.getDocument(currentUser.id);
  UnsavedRevision newRev;
  try {
      newRev = doc.getCurrentRevision().createRevision();
      newRev.setAttachment(
              "profileImage",
              "image/jpg",
              inputStream);
      newRev.save();
  } catch (CouchbaseLiteException e) {
      e.printStackTrace();
  }
```

When i try to upload this image i get this error

Got error status: 403 for {url}/db/{uuid}?new_edits=false.  Reason: Forbidden

Doing the same thing but not calling set attachment with my bitmap allows the doc to upload. Updating any of the properties of the new doc doesn't return a 403, but if you add an attachment it gives a 403 and doesnt sync with server but seems to update locally.

Im on android using couchbase-lite-android:1.0.3

Steps to repo
Attempt to update doc with an attachment. 
Happens in every case we know

Heres a google doc where we discuss it
https://groups.google.com/forum/#!searchin/mobile-couchbase/403$20set$20attachment/mobile-couchbase/KUHqsEju25o/kQ9rDvntjGUJ

Here is the sync gateway configs
```javascript
"log": ["CRUD", "REST+", "Shadow", "Access"],
   "facebook": {
       "register": true
   },
   "CORS": {
       "Origin":["*"],
       "Headers": ["DNT","X-Mx-ReqToken","Keep-Alive","User-Agent","X-Requested-With","If-Modified-Since","Cache-Control","Content-Type"],
       "MaxAge": 1728000
   },
   "databases": {
       "todos": {
           "server": "http://<hostname>:8091",
           "users": {
               "GUEST": {
                   "disabled": false
               }
           },
```

**Comment by hideki** [comment]
Given sample code uses `setHeaders(Map<String, String>)` to set sessionID. However, CBL recommend to set credential by `setAuthenticator(Authenticator)`. This could cause the issue.
http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/couchbase-lite/replication/replication/index.html#authenticator-authenticator--get-set-

We tested this scenario (Facebook authentication and attachment) by [ToDo-Lite Android](https://github.com/couchbaselabs/ToDoLite-Android/). It works fine with v1.2.0 (version I confirmed).

I will close this ticket. If this issue is still reproducible, please reopen this.
