### ISSUE TITLE
LiveQuery doesn't make a view to refresh when a document is updated

### ISSUE THREAD

**Issue by serandel** [couchbase/couchbase-lite-android#493]
Hi, 

In my app I have a LiveQuery running that gives me a subset of my model.

Sometimes I get an object from it and update it with document.putProperties(updatedProps).

I've noticed that my query doesn't give another result, even if the values emitted in my map function are different. In fact, the map function isn't invoked until I close my query and start another one.

The only thing I can think of is that my queries are made (in this case) with setMapOnly set to true.

Any ideas why is this happening? Thanks!

Test Devices: Nexus 5 (5.0.1 Lolllipop) and Shield Tablet (5.0.1 Lollipop)
Couchbase Lite version: 1.0.3.1 and 1.0.4

**Comment by serandel** [comment]
Debugging a little more, what happens is that the change listener added to the database in LiveQuery.start() is not called at all...

**Comment by tleyden** [comment]
This sounds a lot like what is happening in [TodoLite-Android](https://github.com/couchbaselabs/ToDoLite-Android), which is known to be working.  Try this:

* Run the TodoLite-Android sample app
* Set a breakpoint [here](https://github.com/couchbaselabs/ToDoLite-Android/blob/e7cbd07ae29a3543bc9f3943fc4ea645c18183b7/ToDoLite/src/main/java/com/couchbase/todolite/helper/LiveQueryAdapter.java#L33)
* Add and edit items (edit by hitting the checkbox) and notice that your breakpoint will get hit, and the livequery will return a refreshed set of rows.

Assuming that works for you, then you can start looking into the TodoLite-Android codebase to find out what you are differently so we can narrow this down.

I'm going to to assume its a bug on your side rather than couchbase-lite, since TodoLite-Android works, so I'm closing the ticket.  Feel free to continue the conversation here though, and if we find a bug I will re-open it.
