### ISSUE TITLE
Sporadic test failure of ReplicationTest.testMockPullBulkDocsSyncGw

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-android#544]
I ran the unit tests locally against the feature branch feature/issue_452_thread_leak and sporadically saw the  ReplicationTest.testMockPullBulkDocsSyncGw test fail:

https://gist.github.com/tleyden/2788b12d605a04bc86ee

I'm assuming it's most likely a problem with the test itself rather than the code on the  feature/issue_452_thread_leak branch, so filing a ticket to track this.

**Comment by hideki** [comment]
I usually don't commit submodule to the development branch because it usually causes conflict during merge.
I committed to update CBL Java Core submodule against CBL Android feature/issue_452_thread_leak branch.  Could you please retry unit test against feature/issue_452_thread_leak branch? 

Thanks!

**Comment by tleyden** [comment]
Can no longer reproduce
