### ISSUE TITLE
Memory leak/memory management continuous push

### ISSUE THREAD

**Issue by hegra** [couchbase/couchbase-lite-android#629]
We have an app that a couple of times every minute updates a document of around 100kb. No attachments. We then have continuous sync on. After a couple of hours the app runs out of memory, freezes, crashes, can't open more cursors... A bit different behavior depending on app history apparently. Also if there are a lot of changes to be synced, the app can't even be restored after restart. Just opening it can find more than around 1000 changes and then runs out of memory, before able to sync a single record.

Made the following test code that can reproduce the error depending on the sleep time between writes and the servers response time. http://pastebin.com/3mBsENy1

Expected behavior would be to only sync the last revision or at least not trying to load all non synced revisions into memory at the same time, as it looks now, and therefore completely fail with the sync forever until app reinstall.

Client: both couchbase-lite-android.1.0.4 and couchbase-lite-android:1.1.0-532
Server: Both tested with Sync Gateway 1.0.3 and master(bfb402f)

**Comment by hideki** [comment]
Hi @hegra,

Thank you very much for your report.

From your code snippet.
- Document size: 800KB ( 8byte * 100K) per a doc
- Number of Docs: 4K docs
- Total size: 3.2GB (800KB * 4K)
- Use continuous push replication

As result -> App crashes or causes Out-Of-Memory error

Honestly speak, we did not spend enough time to optimize push replication because most of use-cases are heavier pull replication. I will look into this issue by next major release (v1.2). In general, this kind of problems are pretty challenging to solve.

Thanks!

**Comment by hegra** [comment]
Thanks for looking into it.

Some clarification: It never reaches 4k docs since it usually crashes around a few hundred updates, I just put whatever large number in there. Also it is the same document that is updated all the time. It works very fine if you have 1 second sleep inbetween the pushes since then it is sent successfully to the server and unloaded from memory. The issue is when the writes to local db is faster than the pushes, then the sync tries to load all documents in memory that it would like to push as it looks.
If you try to run the script and play around with the sleep time you will see.

But the main issue is that if the app does not have contact with the server for a long time or the server connection is slow, it makes a long changelist in memory that it will never be able to execute on since it loads all docs into memory before starting pushing. This also happens at restart of the app so that a crashed app will not be able to recover and needs to be reinstalled and thus loose all it's data.

**Comment by hideki** [comment]
Hi @hegra,
Thank you for additional information.
Whenever database has new record/update/delete, it fires DocumentChange notification. It becomes trigger of push replication. Because of too many Change notification, I assume push replication creates many halfway objects in memory for next step (data upload). However, because of slower network, halfway objects kept increasing, then it causes Out-Of-Memory or crash. I will look into it. Please give us time to fix this.
Thanks!

**Comment by hegra** [comment]
Did some more testing today. It looks like if you only create a lot of new documents that are large and then call manual sync on them afterwards, then it also crashes on out of memory (no change notification even fires). Looks like it tries to put all changes it finds in local db into memory and push all of them at same time? Are there no limit on how much data at a time it will try to send?

**Comment by hegra** [comment]
The issue looks likely to be that the buffer overflow code hasn't been ported to java in PusherInternal.java:450

//TODO: port this code from iOS
                                /*
                                bufferedSize += [CBLJSON estimateMemorySize: properties];
                                if (bufferedSize > kMaxBulkDocsObjectSize) {
                                    [self uploadBulkDocs: docsToSend changes: revsToSend];
                                    docsToSend = $marray();
                                    revsToSend = [[CBL_RevisionList alloc] init];
                                    bufferedSize = 0;
                                }
                                */

**Comment by hideki** [comment]
note to self:

simplest scenario to reproduce this issue:
1. Create 2000  11KB documents at a device. (w/wo Transaction does not matter.)
2. Start push replication (continuous/not-continuous does not matter)
3. After around 1500 doc changes are handled, Out of memory error occurs.

Note: Used Genymotion.
