### ISSUE TITLE
Document local update vs Channel added(Server) to same document update.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-android#653]
Hi Folks,

  Assume
 a)Document A is added to local database.
b) UI is Updated with that doc data on DB change callback.
c) At server Document A is updated with channel info to say to whom it belongs to.
d)Now after the channel is added the the same document is getting reflected to Client A.
e)Is there a flag/Property to identify this event on DB change?
f)Need to avoid UI getting updated with the same document.

	public void changed(ChangeEvent Event) {
		
	}
How does the ChangeEvent .isExternal() works? Also how is the ChangeEvent.getChanges() values filled while DB changed callback is given?

We have seen getChanges() giving multiple values in same callback, then hows isExternal() works?

Thanks
Nithin

**Comment by hideki** [comment]
HI @NitzDKoder 

isExternal() should return true if a change is originally come not from a local DB. Actually it is through a replicator from SG, CouchDB, or P2P.

Note: For question, I recommend to post a question on https://forums.couchbase.com/c/mobile because Forum is observed by more people. You might receive response/answer quickly.

Thanks,
Hideki

**Comment by pasin** [comment]
DocumentChange also has the source property that you can use to check where the change came from. If it's from the remote server, the source would be the URL of the remote server.

**Comment by hideki** [comment]
Hi @NitzDKoder,
Do you have enough information about your question?

**Comment by hideki** [comment]
I hope our answer satisfied user's question. I will close this ticket.
